name = "MuesliMaterialsWrapper_jll"
uuid = "6dead231-e870-550e-b74b-2a3bf2cfaa53"
version = "0.13.2+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
MuesliMaterials_jll = "ef259003-9f3a-5fc7-ae68-dce6b88dc7d6"

[compat]
JLLWrappers = "1.2.0"
julia = "~1.10, ~1.11, ~1.12"
libcxxwrap_julia_jll = "~0.14.3"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
MuesliMaterials_jll = "1.16"
